# refer to http://www.yaml.org/spec/1.1/ for clarification on YAML collections
apparelrow:
  path: apparelrow/media/styles
  custom_css:
    ie.css:
      - ../../../blueprint/apparelrow_ie.css
    print.css:
      - ../../../blueprint/apparelrow_print.css
    screen.css:
      - ../../../blueprint/apparelrow_screen.css
  custom_layout:
    column_count: 24
    column_width: 20
    gutter_width: 20
  semantic_classes:
    "#header": ".span-24"
    "#nav": ".span-24"
    "#content": ".column .span-16"
    "#extra-content": ".column .span-8, last"
